project:
  type: website
  render:
    - preface.qmd
    - 01_intro/02_license.qmd
    - index.qmd
    - model.ipynb
    - about.qmd

# theme:
#   light: flatly
#   dark: darkly
    
website:
  title: "Urgent Care Calls Sim"
  repo-url: https://github.com/pythonhealthdatascience/ciw_shinyapp
  repo-actions: [edit, issue]
  sidebar:
    style: "docked"
    search: true
    contents:
      - preface.qmd
      - section: "Introduction"
        contents:
          - 01_intro/02_license.qmd
          - index.qmd
          - about.qmd
      - section: "Model"
        contents:
          - model.ipynb
 

  # navbar:
  #   left:
  #     - href: index.qmd
  #       text: Home
  #     - model.ipynb
  #     - about.qmd
    tools:
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/pythonhealthdatascience/ciw_shinyapp
          - text: Report a Bug
            url:  https://github.com/pythonhealthdatascience/ciw_shinyapp/issues
      - icon: rocket-takeoff-fill
        menu:
          - text: Launch in Binder
            url: https://mybinder.org/v2/gh/pythonhealthdatascience/ciw_shinyapp/HEAD


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



