name: stars_pyshiny
channels:
  - conda-forge
dependencies:
  - matplotlib=3.7.1
  - numpy=1.25.0
  - pandas=2.0.2
  - plotly=5.15.0
  - pip=23.1.2
  - python=3.9.16
  - scipy=1.10.1
  - pip:
    - ciw==2.3.1
    - shiny==0.4.0
    - shinyswatch==0.2.4
    - shinywidgets==0.2.1
    - rsconnect-python==1.19.1
