name: stars_pyshiny
channels:
  - conda-forge
dependencies:
  - matplotlib=3.7.1
  - numpy=1.25.0
  - pandas=2.0.2
  - plotly=5.15.0
  - pip=23.1.2
  - python=3.9.16
  - scipy=1.10.1
  - pip:
    - ciw==2.3.1
    - faicons==0.2.2
    - shiny==1.1.0
    - shinyswatch==0.7.0
    - shinywidgets==0.3.3
    - rsconnect-python==1.24.0
